import type { NodeTemplate } from './workflow';

export const nodeTemplates: NodeTemplate[] = [
  {
    type: 'voice-input',
    label: 'Voice Input',
    description: 'Capture voice from caller',
    icon: 'mic',
    category: 'input',
    defaultData: {
      language: 'en-US',
      sampleRate: 16000,
      vadEnabled: true,
    },
    defaultInputs: [],
    defaultOutputs: [{ id: 'audio-out', type: 'output', label: 'Audio' }],
  },
  {
    type: 'ai-model',
    label: 'AI Model',
    description: 'Configure LLM with prompts',
    icon: 'bot',
    category: 'processing',
    defaultData: {
      modelName: 'gpt-4',
      provider: 'openai',
      systemPrompt: '',
      temperature: 0.7,
      maxTokens: 1024,
      apiKeyConfigured: false,
    },
    defaultInputs: [{ id: 'text-in', type: 'input', label: 'Input' }],
    defaultOutputs: [{ id: 'text-out', type: 'output', label: 'Response' }],
  },
  {
    type: 'rag-documents',
    label: 'RAG Documents',
    description: 'Upload & index documents',
    icon: 'file-text',
    category: 'data',
    defaultData: {
      documents: [],
      chunkSize: 512,
      chunkOverlap: 50,
      embeddingModel: 'text-embedding-3-small',
    },
    defaultInputs: [{ id: 'query-in', type: 'input', label: 'Query' }],
    defaultOutputs: [{ id: 'context-out', type: 'output', label: 'Context' }],
  },
  {
    type: 'google-sheets',
    label: 'Google Sheets',
    description: 'Read/write spreadsheet data',
    icon: 'table',
    category: 'data',
    defaultData: {
      spreadsheetId: '',
      sheetName: '',
      range: 'A1:Z100',
      credentials: false,
      syncMode: 'read',
    },
    defaultInputs: [{ id: 'data-in', type: 'input', label: 'Data' }],
    defaultOutputs: [{ id: 'data-out', type: 'output', label: 'Data' }],
  },
  {
    type: 'voice-output',
    label: 'Voice Output',
    description: 'Text-to-speech response',
    icon: 'volume',
    category: 'output',
    defaultData: {
      voice: 'alloy',
      speed: 1.0,
      pitch: 1.0,
    },
    defaultInputs: [{ id: 'text-in', type: 'input', label: 'Text' }],
    defaultOutputs: [],
  },
];
