import type { NodeTemplate } from './workflow';

export const nodeTemplates: NodeTemplate[] = [
  {
    type: 'voice-input',
    label: 'Voice Input',
    description: 'Capture voice from caller',
    icon: 'mic',
    category: 'input',
    defaultData: {
      language: 'en-US',
      sampleRate: 16000,
      vadEnabled: true,
    },
    defaultInputs: [],
    defaultOutputs: [{ id: 'audio-out', type: 'output', position: 'right', label: 'Output' }],
  },
  {
    type: 'text-input',
    label: 'Text Input',
    description: 'Simple text input for manual or system-provided text',
    icon: 'file-text',
    category: 'input',
    defaultData: {
      placeholder: 'Enter text...',
      allowMultiline: false,
      maxLength: 200,
    },
    defaultInputs: [],
    defaultOutputs: [{ id: 'text-out', type: 'output', position: 'right', label: 'Output' }],
  },
  {
    type: 'ai-model',
    label: 'AI Model',
    description: 'Configure LLM with prompts',
    icon: 'bot',
    category: 'processing',
    defaultData: {
      modelName: 'gpt-4',
      provider: 'openai',
      systemPrompt: '',
      temperature: 0.7,
      maxTokens: 1024,
      apiKeyConfigured: false,
    },
    defaultInputs: [
      { id: 'text-in', type: 'input', position: 'left', label: 'Input' },
      { id: 'context-in', type: 'input', position: 'bottom', label: 'Context' },
    ],
    defaultOutputs: [{ id: 'text-out', type: 'output', position: 'right', label: 'Output' }],
  },
  {
    type: 'rag-documents',
    label: 'RAG Documents',
    description: 'Upload & index documents for context',
    icon: 'file-text',
    category: 'data',
    defaultData: {
      documents: [],
      chunkSize: 512,
      chunkOverlap: 50,
      embeddingModel: 'text-embedding-3-small',
    },
    defaultInputs: [],
    defaultOutputs: [{ id: 'context-out', type: 'output', position: 'right', label: 'Context' }],
  },
  {
    type: 'google-sheets',
    label: 'Google Sheets',
    description: 'Read/write spreadsheet data',
    icon: 'table',
    category: 'data',
    defaultData: {
      spreadsheetId: '',
      sheetName: '',
      range: 'A1:Z100',
      credentials: false,
      syncMode: 'read',
    },
    defaultInputs: [{ id: 'data-in', type: 'input', position: 'left', label: 'Input' }],
    defaultOutputs: [{ id: 'data-out', type: 'output', position: 'right', label: 'Output' }],
  },
  {
    type: 'voice-output',
    label: 'Voice Output',
    description: 'Text-to-speech response',
    icon: 'volume',
    category: 'output',
    defaultData: {
      voice: 'alloy',
      speed: 1.0,
      pitch: 1.0,
    },
    defaultInputs: [{ id: 'text-in', type: 'input', position: 'left', label: 'Input' }],
    defaultOutputs: [],
  },
  {
    type: 'text-output',
    label: 'Text Output',
    description: 'Display or forward text output',
    icon: 'file-text',
    category: 'output',
    defaultData: {
      format: 'plain',
      truncateLength: 0,
    },
    defaultInputs: [{ id: 'text-in', type: 'input', position: 'left', label: 'Input' }],
    defaultOutputs: [],
  },
  {
    type: 'if-condition',
    label: 'If Condition',
    description: 'Branch based on conditions',
    icon: 'git-branch',
    category: 'processing',
    defaultData: {
      conditionType: 'contains',
      conditionValue: '',
      caseSensitive: false,
      customExpression: '',
      field: 'response', // Default to checking AI response
    },
    defaultInputs: [{ id: 'value-in', type: 'input', position: 'left', label: 'Input' }],
    defaultOutputs: [
      { id: 'true-out', type: 'output', position: 'right', label: 'True' },
      { id: 'false-out', type: 'output', position: 'right', label: 'False' },
    ],
  },
];
